// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.19.1
// source: v0/contract.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation
} from '@grpc/grpc-js'

export const protobufPackage = 'v0'

export interface HealthRequest {
  payload: string
}

export interface HealthResponse {
  payload: string
  data: string
}

/** Stored OPAQUE registration record (reconstructed from database fields). */
export interface OpaqueRecord {
  /** Ed25519 signing public key — 32 bytes */
  clientEd25519PublicKey: Uint8Array
  /** X25519 long-term public key — 32 bytes */
  clientX25519PublicKey: Uint8Array
  /** Envelope masking key — 64 bytes (Nh) */
  maskingKey: Uint8Array
  /** Envelope nonce — 32 bytes (Nn) */
  envelopeNonce: Uint8Array
  /** Envelope HMAC-SHA512 tag — 64 bytes (Nm) */
  envelopeAuthTag: Uint8Array
  /** Encrypted client keypair seed — 32 bytes (Nseed) */
  envelopeSeed: Uint8Array
}

/** Client credential request: blinded password sent to server for OPRF evaluation. */
export interface OpaqueCredentialRequest {
  /** ristretto255 point (blinded password) — 32 bytes (Noe) */
  blindedMessage: Uint8Array
}

/** Client auth request: ephemeral keyshare + nonce (part of KE1). */
export interface OpaqueAuthRequest {
  /** Random nonce — 32 bytes (Nn) */
  clientNonce: Uint8Array
  /** Ephemeral X25519 public key — 32 bytes (Npk) */
  clientX25519PublicKeyshare: Uint8Array
}

/** KE1: client's first AKE message (credential request + auth request). */
export interface OpaqueKe1 {
  credentialRequest: OpaqueCredentialRequest | undefined
  authRequest: OpaqueAuthRequest | undefined
}

/**
 * Server credential response: evaluated OPRF output + masked envelope.
 * masked_response size = Npk + Nn + Nm + Nseed = 32+32+64+32 = 160 bytes
 */
export interface OpaqueCredentialResponse {
  /** ristretto255 element (OPRF output) — 32 bytes (Noe) */
  evaluatedMessage: Uint8Array
  /** Random nonce for credential masking — 32 bytes (Nn) */
  maskingNonce: Uint8Array
  /** XOR-masked (serverPublicKey || envelope) — 160 bytes */
  maskedResponse: Uint8Array
}

/** Server auth response: ephemeral keyshare + nonce + MAC (part of KE2). */
export interface OpaqueAuthResponse {
  /** Random nonce — 32 bytes (Nn) */
  serverNonce: Uint8Array
  /** Ephemeral X25519 public key — 32 bytes (Npk) */
  serverX25519PublicKeyshare: Uint8Array
  /** HMAC-SHA512 server authentication tag — 64 bytes (Nm) */
  serverMac: Uint8Array
}

/** KE2: server's AKE message (credential response + auth response). */
export interface OpaqueKe2 {
  credentialResponse: OpaqueCredentialResponse | undefined
  authResponse: OpaqueAuthResponse | undefined
}

export interface CreateRegistrationResponseRequest {
  /** Client's blinded password (ristretto255 point, 32 bytes). */
  blindedMessage: Uint8Array
  /**
   * Unique per-credential identifier used to derive the OPRF key from OPAQUE_SEED.
   * Max 256 bytes. Typically: user's credential identifier bytes stored in DB.
   */
  credentialIdentifier: Uint8Array
}

export interface CreateRegistrationResponseReply {
  /** OPRF-evaluated element: blindedMessage * oprfKey (ristretto255 point, 32 bytes). */
  evaluatedMessage: Uint8Array
  /**
   * Server's long-term X25519 public key (32 bytes).
   * Loaded from OPAQUE_SERVER_PUBLIC_KEY env var.
   */
  serverPublicKey: Uint8Array
}

export interface GenerateKE2Request {
  /** The stored OPAQUE registration record for this credential (from database). */
  record: OpaqueRecord | undefined
  /** Credential identifier used to derive the per-credential OPRF key. */
  credentialIdentifier: Uint8Array
  /** KE1 message received from the client. */
  ke1: OpaqueKe1 | undefined
  /** Optional server identity override (empty bytes = default to server public key). */
  serverIdentity: Uint8Array
  /** Optional client identity override (empty bytes = default to client public key). */
  clientIdentity: Uint8Array
}

export interface GenerateKE2Reply {
  /** KE2 message to return to the client. */
  ke2: OpaqueKe2 | undefined
  /**
   * Server state for KE3 verification — persist in Redis with short TTL (5 min).
   * expectedClientMac: the HMAC the client must produce to authenticate — 64 bytes.
   */
  expectedClientMac: Uint8Array
  /**
   * sessionKey: the shared session key established via triple-DH — 64 bytes.
   * Used for channel encryption (AES-256-GCM) after successful authentication.
   */
  sessionKey: Uint8Array
}

export interface ServerFinishRequest {
  /** Client MAC from KE3 message (ke3.clientMac) — 64 bytes (Nm). */
  ke3ClientMac: Uint8Array
  /** Expected client MAC from Redis state (produced during GenerateKE2) — 64 bytes. */
  expectedClientMac: Uint8Array
}

export interface ServerFinishReply {
  /** true if MACs match (constant-time comparison); false if authentication fails. */
  valid: boolean
}

export interface CreateChangePasswordResponseRequest {
  /** Credential identifier for looking up the stored record. */
  credentialIdentifier: Uint8Array
  /** KE1 for old password authentication (proves knowledge of current password). */
  oldPasswordKe1: OpaqueKe1 | undefined
  /** Registration request for the new password (blinded new password for OPRF). */
  newPasswordRegRequest: OpaqueCredentialRequest | undefined
  /** The stored OPAQUE registration record for the current password (from database). */
  record: OpaqueRecord | undefined
  /** Optional server identity override (empty bytes = default to server public key). */
  serverIdentity: Uint8Array
  /** Optional client identity override (empty bytes = default to client public key). */
  clientIdentity: Uint8Array
}

export interface CreateChangePasswordResponseReply {
  /** KE2 for old password — client must verify server MAC and produce KE3. */
  oldPasswordKe2: OpaqueKe2 | undefined
  /** Server state for KE3 verification — persist in Redis with short TTL. */
  expectedClientMac: Uint8Array
  /** 64 bytes */
  sessionKey: Uint8Array
  /** New password registration response — client uses this to finalize new envelope. */
  newEvaluatedMessage: Uint8Array
  /** X25519 public key — 32 bytes */
  newServerPublicKey: Uint8Array
}

function createBaseHealthRequest(): HealthRequest {
  return { payload: '' }
}

export const HealthRequest: MessageFns<HealthRequest> = {
  encode(message: HealthRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload !== '') {
      writer.uint32(10).string(message.payload)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseHealthRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.payload = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): HealthRequest {
    return { payload: isSet(object.payload) ? globalThis.String(object.payload) : '' }
  },

  toJSON(message: HealthRequest): unknown {
    const obj: any = {}
    if (message.payload !== '') {
      obj.payload = message.payload
    }
    return obj
  },

  create<I extends Exact<DeepPartial<HealthRequest>, I>>(base?: I): HealthRequest {
    return HealthRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<HealthRequest>, I>>(object: I): HealthRequest {
    const message = createBaseHealthRequest()
    message.payload = object.payload ?? ''
    return message
  }
}

function createBaseHealthResponse(): HealthResponse {
  return { payload: '', data: '' }
}

export const HealthResponse: MessageFns<HealthResponse> = {
  encode(message: HealthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload !== '') {
      writer.uint32(10).string(message.payload)
    }
    if (message.data !== '') {
      writer.uint32(18).string(message.data)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseHealthResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.payload = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.data = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): HealthResponse {
    return {
      payload: isSet(object.payload) ? globalThis.String(object.payload) : '',
      data: isSet(object.data) ? globalThis.String(object.data) : ''
    }
  },

  toJSON(message: HealthResponse): unknown {
    const obj: any = {}
    if (message.payload !== '') {
      obj.payload = message.payload
    }
    if (message.data !== '') {
      obj.data = message.data
    }
    return obj
  },

  create<I extends Exact<DeepPartial<HealthResponse>, I>>(base?: I): HealthResponse {
    return HealthResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<HealthResponse>, I>>(object: I): HealthResponse {
    const message = createBaseHealthResponse()
    message.payload = object.payload ?? ''
    message.data = object.data ?? ''
    return message
  }
}

function createBaseOpaqueRecord(): OpaqueRecord {
  return {
    clientEd25519PublicKey: new Uint8Array(0),
    clientX25519PublicKey: new Uint8Array(0),
    maskingKey: new Uint8Array(0),
    envelopeNonce: new Uint8Array(0),
    envelopeAuthTag: new Uint8Array(0),
    envelopeSeed: new Uint8Array(0)
  }
}

export const OpaqueRecord: MessageFns<OpaqueRecord> = {
  encode(message: OpaqueRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientEd25519PublicKey.length !== 0) {
      writer.uint32(10).bytes(message.clientEd25519PublicKey)
    }
    if (message.clientX25519PublicKey.length !== 0) {
      writer.uint32(18).bytes(message.clientX25519PublicKey)
    }
    if (message.maskingKey.length !== 0) {
      writer.uint32(26).bytes(message.maskingKey)
    }
    if (message.envelopeNonce.length !== 0) {
      writer.uint32(34).bytes(message.envelopeNonce)
    }
    if (message.envelopeAuthTag.length !== 0) {
      writer.uint32(42).bytes(message.envelopeAuthTag)
    }
    if (message.envelopeSeed.length !== 0) {
      writer.uint32(50).bytes(message.envelopeSeed)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpaqueRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseOpaqueRecord()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.clientEd25519PublicKey = reader.bytes()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.clientX25519PublicKey = reader.bytes()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.maskingKey = reader.bytes()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.envelopeNonce = reader.bytes()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.envelopeAuthTag = reader.bytes()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.envelopeSeed = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): OpaqueRecord {
    return {
      clientEd25519PublicKey: isSet(object.clientEd25519PublicKey)
        ? bytesFromBase64(object.clientEd25519PublicKey)
        : isSet(object.client_ed25519_public_key)
          ? bytesFromBase64(object.client_ed25519_public_key)
          : new Uint8Array(0),
      clientX25519PublicKey: isSet(object.clientX25519PublicKey)
        ? bytesFromBase64(object.clientX25519PublicKey)
        : isSet(object.client_x25519_public_key)
          ? bytesFromBase64(object.client_x25519_public_key)
          : new Uint8Array(0),
      maskingKey: isSet(object.maskingKey) ? bytesFromBase64(object.maskingKey) : isSet(object.masking_key) ? bytesFromBase64(object.masking_key) : new Uint8Array(0),
      envelopeNonce: isSet(object.envelopeNonce) ? bytesFromBase64(object.envelopeNonce) : isSet(object.envelope_nonce) ? bytesFromBase64(object.envelope_nonce) : new Uint8Array(0),
      envelopeAuthTag: isSet(object.envelopeAuthTag) ? bytesFromBase64(object.envelopeAuthTag) : isSet(object.envelope_auth_tag) ? bytesFromBase64(object.envelope_auth_tag) : new Uint8Array(0),
      envelopeSeed: isSet(object.envelopeSeed) ? bytesFromBase64(object.envelopeSeed) : isSet(object.envelope_seed) ? bytesFromBase64(object.envelope_seed) : new Uint8Array(0)
    }
  },

  toJSON(message: OpaqueRecord): unknown {
    const obj: any = {}
    if (message.clientEd25519PublicKey.length !== 0) {
      obj.clientEd25519PublicKey = base64FromBytes(message.clientEd25519PublicKey)
    }
    if (message.clientX25519PublicKey.length !== 0) {
      obj.clientX25519PublicKey = base64FromBytes(message.clientX25519PublicKey)
    }
    if (message.maskingKey.length !== 0) {
      obj.maskingKey = base64FromBytes(message.maskingKey)
    }
    if (message.envelopeNonce.length !== 0) {
      obj.envelopeNonce = base64FromBytes(message.envelopeNonce)
    }
    if (message.envelopeAuthTag.length !== 0) {
      obj.envelopeAuthTag = base64FromBytes(message.envelopeAuthTag)
    }
    if (message.envelopeSeed.length !== 0) {
      obj.envelopeSeed = base64FromBytes(message.envelopeSeed)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<OpaqueRecord>, I>>(base?: I): OpaqueRecord {
    return OpaqueRecord.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<OpaqueRecord>, I>>(object: I): OpaqueRecord {
    const message = createBaseOpaqueRecord()
    message.clientEd25519PublicKey = object.clientEd25519PublicKey ?? new Uint8Array(0)
    message.clientX25519PublicKey = object.clientX25519PublicKey ?? new Uint8Array(0)
    message.maskingKey = object.maskingKey ?? new Uint8Array(0)
    message.envelopeNonce = object.envelopeNonce ?? new Uint8Array(0)
    message.envelopeAuthTag = object.envelopeAuthTag ?? new Uint8Array(0)
    message.envelopeSeed = object.envelopeSeed ?? new Uint8Array(0)
    return message
  }
}

function createBaseOpaqueCredentialRequest(): OpaqueCredentialRequest {
  return { blindedMessage: new Uint8Array(0) }
}

export const OpaqueCredentialRequest: MessageFns<OpaqueCredentialRequest> = {
  encode(message: OpaqueCredentialRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blindedMessage.length !== 0) {
      writer.uint32(10).bytes(message.blindedMessage)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpaqueCredentialRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseOpaqueCredentialRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.blindedMessage = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): OpaqueCredentialRequest {
    return {
      blindedMessage: isSet(object.blindedMessage) ? bytesFromBase64(object.blindedMessage) : isSet(object.blinded_message) ? bytesFromBase64(object.blinded_message) : new Uint8Array(0)
    }
  },

  toJSON(message: OpaqueCredentialRequest): unknown {
    const obj: any = {}
    if (message.blindedMessage.length !== 0) {
      obj.blindedMessage = base64FromBytes(message.blindedMessage)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<OpaqueCredentialRequest>, I>>(base?: I): OpaqueCredentialRequest {
    return OpaqueCredentialRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<OpaqueCredentialRequest>, I>>(object: I): OpaqueCredentialRequest {
    const message = createBaseOpaqueCredentialRequest()
    message.blindedMessage = object.blindedMessage ?? new Uint8Array(0)
    return message
  }
}

function createBaseOpaqueAuthRequest(): OpaqueAuthRequest {
  return { clientNonce: new Uint8Array(0), clientX25519PublicKeyshare: new Uint8Array(0) }
}

export const OpaqueAuthRequest: MessageFns<OpaqueAuthRequest> = {
  encode(message: OpaqueAuthRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientNonce.length !== 0) {
      writer.uint32(10).bytes(message.clientNonce)
    }
    if (message.clientX25519PublicKeyshare.length !== 0) {
      writer.uint32(18).bytes(message.clientX25519PublicKeyshare)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpaqueAuthRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseOpaqueAuthRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.clientNonce = reader.bytes()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.clientX25519PublicKeyshare = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): OpaqueAuthRequest {
    return {
      clientNonce: isSet(object.clientNonce) ? bytesFromBase64(object.clientNonce) : isSet(object.client_nonce) ? bytesFromBase64(object.client_nonce) : new Uint8Array(0),
      clientX25519PublicKeyshare: isSet(object.clientX25519PublicKeyshare)
        ? bytesFromBase64(object.clientX25519PublicKeyshare)
        : isSet(object.client_x25519_public_keyshare)
          ? bytesFromBase64(object.client_x25519_public_keyshare)
          : new Uint8Array(0)
    }
  },

  toJSON(message: OpaqueAuthRequest): unknown {
    const obj: any = {}
    if (message.clientNonce.length !== 0) {
      obj.clientNonce = base64FromBytes(message.clientNonce)
    }
    if (message.clientX25519PublicKeyshare.length !== 0) {
      obj.clientX25519PublicKeyshare = base64FromBytes(message.clientX25519PublicKeyshare)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<OpaqueAuthRequest>, I>>(base?: I): OpaqueAuthRequest {
    return OpaqueAuthRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<OpaqueAuthRequest>, I>>(object: I): OpaqueAuthRequest {
    const message = createBaseOpaqueAuthRequest()
    message.clientNonce = object.clientNonce ?? new Uint8Array(0)
    message.clientX25519PublicKeyshare = object.clientX25519PublicKeyshare ?? new Uint8Array(0)
    return message
  }
}

function createBaseOpaqueKe1(): OpaqueKe1 {
  return { credentialRequest: undefined, authRequest: undefined }
}

export const OpaqueKe1: MessageFns<OpaqueKe1> = {
  encode(message: OpaqueKe1, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.credentialRequest !== undefined) {
      OpaqueCredentialRequest.encode(message.credentialRequest, writer.uint32(10).fork()).join()
    }
    if (message.authRequest !== undefined) {
      OpaqueAuthRequest.encode(message.authRequest, writer.uint32(18).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpaqueKe1 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseOpaqueKe1()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.credentialRequest = OpaqueCredentialRequest.decode(reader, reader.uint32())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.authRequest = OpaqueAuthRequest.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): OpaqueKe1 {
    return {
      credentialRequest: isSet(object.credentialRequest)
        ? OpaqueCredentialRequest.fromJSON(object.credentialRequest)
        : isSet(object.credential_request)
          ? OpaqueCredentialRequest.fromJSON(object.credential_request)
          : undefined,
      authRequest: isSet(object.authRequest) ? OpaqueAuthRequest.fromJSON(object.authRequest) : isSet(object.auth_request) ? OpaqueAuthRequest.fromJSON(object.auth_request) : undefined
    }
  },

  toJSON(message: OpaqueKe1): unknown {
    const obj: any = {}
    if (message.credentialRequest !== undefined) {
      obj.credentialRequest = OpaqueCredentialRequest.toJSON(message.credentialRequest)
    }
    if (message.authRequest !== undefined) {
      obj.authRequest = OpaqueAuthRequest.toJSON(message.authRequest)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<OpaqueKe1>, I>>(base?: I): OpaqueKe1 {
    return OpaqueKe1.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<OpaqueKe1>, I>>(object: I): OpaqueKe1 {
    const message = createBaseOpaqueKe1()
    message.credentialRequest = object.credentialRequest !== undefined && object.credentialRequest !== null ? OpaqueCredentialRequest.fromPartial(object.credentialRequest) : undefined
    message.authRequest = object.authRequest !== undefined && object.authRequest !== null ? OpaqueAuthRequest.fromPartial(object.authRequest) : undefined
    return message
  }
}

function createBaseOpaqueCredentialResponse(): OpaqueCredentialResponse {
  return { evaluatedMessage: new Uint8Array(0), maskingNonce: new Uint8Array(0), maskedResponse: new Uint8Array(0) }
}

export const OpaqueCredentialResponse: MessageFns<OpaqueCredentialResponse> = {
  encode(message: OpaqueCredentialResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.evaluatedMessage.length !== 0) {
      writer.uint32(10).bytes(message.evaluatedMessage)
    }
    if (message.maskingNonce.length !== 0) {
      writer.uint32(18).bytes(message.maskingNonce)
    }
    if (message.maskedResponse.length !== 0) {
      writer.uint32(26).bytes(message.maskedResponse)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpaqueCredentialResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseOpaqueCredentialResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.evaluatedMessage = reader.bytes()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.maskingNonce = reader.bytes()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.maskedResponse = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): OpaqueCredentialResponse {
    return {
      evaluatedMessage: isSet(object.evaluatedMessage) ? bytesFromBase64(object.evaluatedMessage) : isSet(object.evaluated_message) ? bytesFromBase64(object.evaluated_message) : new Uint8Array(0),
      maskingNonce: isSet(object.maskingNonce) ? bytesFromBase64(object.maskingNonce) : isSet(object.masking_nonce) ? bytesFromBase64(object.masking_nonce) : new Uint8Array(0),
      maskedResponse: isSet(object.maskedResponse) ? bytesFromBase64(object.maskedResponse) : isSet(object.masked_response) ? bytesFromBase64(object.masked_response) : new Uint8Array(0)
    }
  },

  toJSON(message: OpaqueCredentialResponse): unknown {
    const obj: any = {}
    if (message.evaluatedMessage.length !== 0) {
      obj.evaluatedMessage = base64FromBytes(message.evaluatedMessage)
    }
    if (message.maskingNonce.length !== 0) {
      obj.maskingNonce = base64FromBytes(message.maskingNonce)
    }
    if (message.maskedResponse.length !== 0) {
      obj.maskedResponse = base64FromBytes(message.maskedResponse)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<OpaqueCredentialResponse>, I>>(base?: I): OpaqueCredentialResponse {
    return OpaqueCredentialResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<OpaqueCredentialResponse>, I>>(object: I): OpaqueCredentialResponse {
    const message = createBaseOpaqueCredentialResponse()
    message.evaluatedMessage = object.evaluatedMessage ?? new Uint8Array(0)
    message.maskingNonce = object.maskingNonce ?? new Uint8Array(0)
    message.maskedResponse = object.maskedResponse ?? new Uint8Array(0)
    return message
  }
}

function createBaseOpaqueAuthResponse(): OpaqueAuthResponse {
  return {
    serverNonce: new Uint8Array(0),
    serverX25519PublicKeyshare: new Uint8Array(0),
    serverMac: new Uint8Array(0)
  }
}

export const OpaqueAuthResponse: MessageFns<OpaqueAuthResponse> = {
  encode(message: OpaqueAuthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverNonce.length !== 0) {
      writer.uint32(10).bytes(message.serverNonce)
    }
    if (message.serverX25519PublicKeyshare.length !== 0) {
      writer.uint32(18).bytes(message.serverX25519PublicKeyshare)
    }
    if (message.serverMac.length !== 0) {
      writer.uint32(26).bytes(message.serverMac)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpaqueAuthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseOpaqueAuthResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.serverNonce = reader.bytes()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.serverX25519PublicKeyshare = reader.bytes()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.serverMac = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): OpaqueAuthResponse {
    return {
      serverNonce: isSet(object.serverNonce) ? bytesFromBase64(object.serverNonce) : isSet(object.server_nonce) ? bytesFromBase64(object.server_nonce) : new Uint8Array(0),
      serverX25519PublicKeyshare: isSet(object.serverX25519PublicKeyshare)
        ? bytesFromBase64(object.serverX25519PublicKeyshare)
        : isSet(object.server_x25519_public_keyshare)
          ? bytesFromBase64(object.server_x25519_public_keyshare)
          : new Uint8Array(0),
      serverMac: isSet(object.serverMac) ? bytesFromBase64(object.serverMac) : isSet(object.server_mac) ? bytesFromBase64(object.server_mac) : new Uint8Array(0)
    }
  },

  toJSON(message: OpaqueAuthResponse): unknown {
    const obj: any = {}
    if (message.serverNonce.length !== 0) {
      obj.serverNonce = base64FromBytes(message.serverNonce)
    }
    if (message.serverX25519PublicKeyshare.length !== 0) {
      obj.serverX25519PublicKeyshare = base64FromBytes(message.serverX25519PublicKeyshare)
    }
    if (message.serverMac.length !== 0) {
      obj.serverMac = base64FromBytes(message.serverMac)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<OpaqueAuthResponse>, I>>(base?: I): OpaqueAuthResponse {
    return OpaqueAuthResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<OpaqueAuthResponse>, I>>(object: I): OpaqueAuthResponse {
    const message = createBaseOpaqueAuthResponse()
    message.serverNonce = object.serverNonce ?? new Uint8Array(0)
    message.serverX25519PublicKeyshare = object.serverX25519PublicKeyshare ?? new Uint8Array(0)
    message.serverMac = object.serverMac ?? new Uint8Array(0)
    return message
  }
}

function createBaseOpaqueKe2(): OpaqueKe2 {
  return { credentialResponse: undefined, authResponse: undefined }
}

export const OpaqueKe2: MessageFns<OpaqueKe2> = {
  encode(message: OpaqueKe2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.credentialResponse !== undefined) {
      OpaqueCredentialResponse.encode(message.credentialResponse, writer.uint32(10).fork()).join()
    }
    if (message.authResponse !== undefined) {
      OpaqueAuthResponse.encode(message.authResponse, writer.uint32(18).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpaqueKe2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseOpaqueKe2()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.credentialResponse = OpaqueCredentialResponse.decode(reader, reader.uint32())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.authResponse = OpaqueAuthResponse.decode(reader, reader.uint32())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): OpaqueKe2 {
    return {
      credentialResponse: isSet(object.credentialResponse)
        ? OpaqueCredentialResponse.fromJSON(object.credentialResponse)
        : isSet(object.credential_response)
          ? OpaqueCredentialResponse.fromJSON(object.credential_response)
          : undefined,
      authResponse: isSet(object.authResponse) ? OpaqueAuthResponse.fromJSON(object.authResponse) : isSet(object.auth_response) ? OpaqueAuthResponse.fromJSON(object.auth_response) : undefined
    }
  },

  toJSON(message: OpaqueKe2): unknown {
    const obj: any = {}
    if (message.credentialResponse !== undefined) {
      obj.credentialResponse = OpaqueCredentialResponse.toJSON(message.credentialResponse)
    }
    if (message.authResponse !== undefined) {
      obj.authResponse = OpaqueAuthResponse.toJSON(message.authResponse)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<OpaqueKe2>, I>>(base?: I): OpaqueKe2 {
    return OpaqueKe2.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<OpaqueKe2>, I>>(object: I): OpaqueKe2 {
    const message = createBaseOpaqueKe2()
    message.credentialResponse = object.credentialResponse !== undefined && object.credentialResponse !== null ? OpaqueCredentialResponse.fromPartial(object.credentialResponse) : undefined
    message.authResponse = object.authResponse !== undefined && object.authResponse !== null ? OpaqueAuthResponse.fromPartial(object.authResponse) : undefined
    return message
  }
}

function createBaseCreateRegistrationResponseRequest(): CreateRegistrationResponseRequest {
  return { blindedMessage: new Uint8Array(0), credentialIdentifier: new Uint8Array(0) }
}

export const CreateRegistrationResponseRequest: MessageFns<CreateRegistrationResponseRequest> = {
  encode(message: CreateRegistrationResponseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blindedMessage.length !== 0) {
      writer.uint32(10).bytes(message.blindedMessage)
    }
    if (message.credentialIdentifier.length !== 0) {
      writer.uint32(18).bytes(message.credentialIdentifier)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRegistrationResponseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseCreateRegistrationResponseRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.blindedMessage = reader.bytes()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.credentialIdentifier = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): CreateRegistrationResponseRequest {
    return {
      blindedMessage: isSet(object.blindedMessage) ? bytesFromBase64(object.blindedMessage) : isSet(object.blinded_message) ? bytesFromBase64(object.blinded_message) : new Uint8Array(0),
      credentialIdentifier: isSet(object.credentialIdentifier)
        ? bytesFromBase64(object.credentialIdentifier)
        : isSet(object.credential_identifier)
          ? bytesFromBase64(object.credential_identifier)
          : new Uint8Array(0)
    }
  },

  toJSON(message: CreateRegistrationResponseRequest): unknown {
    const obj: any = {}
    if (message.blindedMessage.length !== 0) {
      obj.blindedMessage = base64FromBytes(message.blindedMessage)
    }
    if (message.credentialIdentifier.length !== 0) {
      obj.credentialIdentifier = base64FromBytes(message.credentialIdentifier)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<CreateRegistrationResponseRequest>, I>>(base?: I): CreateRegistrationResponseRequest {
    return CreateRegistrationResponseRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<CreateRegistrationResponseRequest>, I>>(object: I): CreateRegistrationResponseRequest {
    const message = createBaseCreateRegistrationResponseRequest()
    message.blindedMessage = object.blindedMessage ?? new Uint8Array(0)
    message.credentialIdentifier = object.credentialIdentifier ?? new Uint8Array(0)
    return message
  }
}

function createBaseCreateRegistrationResponseReply(): CreateRegistrationResponseReply {
  return { evaluatedMessage: new Uint8Array(0), serverPublicKey: new Uint8Array(0) }
}

export const CreateRegistrationResponseReply: MessageFns<CreateRegistrationResponseReply> = {
  encode(message: CreateRegistrationResponseReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.evaluatedMessage.length !== 0) {
      writer.uint32(10).bytes(message.evaluatedMessage)
    }
    if (message.serverPublicKey.length !== 0) {
      writer.uint32(18).bytes(message.serverPublicKey)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRegistrationResponseReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseCreateRegistrationResponseReply()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.evaluatedMessage = reader.bytes()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.serverPublicKey = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): CreateRegistrationResponseReply {
    return {
      evaluatedMessage: isSet(object.evaluatedMessage) ? bytesFromBase64(object.evaluatedMessage) : isSet(object.evaluated_message) ? bytesFromBase64(object.evaluated_message) : new Uint8Array(0),
      serverPublicKey: isSet(object.serverPublicKey) ? bytesFromBase64(object.serverPublicKey) : isSet(object.server_public_key) ? bytesFromBase64(object.server_public_key) : new Uint8Array(0)
    }
  },

  toJSON(message: CreateRegistrationResponseReply): unknown {
    const obj: any = {}
    if (message.evaluatedMessage.length !== 0) {
      obj.evaluatedMessage = base64FromBytes(message.evaluatedMessage)
    }
    if (message.serverPublicKey.length !== 0) {
      obj.serverPublicKey = base64FromBytes(message.serverPublicKey)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<CreateRegistrationResponseReply>, I>>(base?: I): CreateRegistrationResponseReply {
    return CreateRegistrationResponseReply.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<CreateRegistrationResponseReply>, I>>(object: I): CreateRegistrationResponseReply {
    const message = createBaseCreateRegistrationResponseReply()
    message.evaluatedMessage = object.evaluatedMessage ?? new Uint8Array(0)
    message.serverPublicKey = object.serverPublicKey ?? new Uint8Array(0)
    return message
  }
}

function createBaseGenerateKE2Request(): GenerateKE2Request {
  return {
    record: undefined,
    credentialIdentifier: new Uint8Array(0),
    ke1: undefined,
    serverIdentity: new Uint8Array(0),
    clientIdentity: new Uint8Array(0)
  }
}

export const GenerateKE2Request: MessageFns<GenerateKE2Request> = {
  encode(message: GenerateKE2Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.record !== undefined) {
      OpaqueRecord.encode(message.record, writer.uint32(10).fork()).join()
    }
    if (message.credentialIdentifier.length !== 0) {
      writer.uint32(18).bytes(message.credentialIdentifier)
    }
    if (message.ke1 !== undefined) {
      OpaqueKe1.encode(message.ke1, writer.uint32(26).fork()).join()
    }
    if (message.serverIdentity.length !== 0) {
      writer.uint32(34).bytes(message.serverIdentity)
    }
    if (message.clientIdentity.length !== 0) {
      writer.uint32(42).bytes(message.clientIdentity)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateKE2Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseGenerateKE2Request()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.record = OpaqueRecord.decode(reader, reader.uint32())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.credentialIdentifier = reader.bytes()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.ke1 = OpaqueKe1.decode(reader, reader.uint32())
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.serverIdentity = reader.bytes()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.clientIdentity = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): GenerateKE2Request {
    return {
      record: isSet(object.record) ? OpaqueRecord.fromJSON(object.record) : undefined,
      credentialIdentifier: isSet(object.credentialIdentifier)
        ? bytesFromBase64(object.credentialIdentifier)
        : isSet(object.credential_identifier)
          ? bytesFromBase64(object.credential_identifier)
          : new Uint8Array(0),
      ke1: isSet(object.ke1) ? OpaqueKe1.fromJSON(object.ke1) : undefined,
      serverIdentity: isSet(object.serverIdentity) ? bytesFromBase64(object.serverIdentity) : isSet(object.server_identity) ? bytesFromBase64(object.server_identity) : new Uint8Array(0),
      clientIdentity: isSet(object.clientIdentity) ? bytesFromBase64(object.clientIdentity) : isSet(object.client_identity) ? bytesFromBase64(object.client_identity) : new Uint8Array(0)
    }
  },

  toJSON(message: GenerateKE2Request): unknown {
    const obj: any = {}
    if (message.record !== undefined) {
      obj.record = OpaqueRecord.toJSON(message.record)
    }
    if (message.credentialIdentifier.length !== 0) {
      obj.credentialIdentifier = base64FromBytes(message.credentialIdentifier)
    }
    if (message.ke1 !== undefined) {
      obj.ke1 = OpaqueKe1.toJSON(message.ke1)
    }
    if (message.serverIdentity.length !== 0) {
      obj.serverIdentity = base64FromBytes(message.serverIdentity)
    }
    if (message.clientIdentity.length !== 0) {
      obj.clientIdentity = base64FromBytes(message.clientIdentity)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<GenerateKE2Request>, I>>(base?: I): GenerateKE2Request {
    return GenerateKE2Request.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<GenerateKE2Request>, I>>(object: I): GenerateKE2Request {
    const message = createBaseGenerateKE2Request()
    message.record = object.record !== undefined && object.record !== null ? OpaqueRecord.fromPartial(object.record) : undefined
    message.credentialIdentifier = object.credentialIdentifier ?? new Uint8Array(0)
    message.ke1 = object.ke1 !== undefined && object.ke1 !== null ? OpaqueKe1.fromPartial(object.ke1) : undefined
    message.serverIdentity = object.serverIdentity ?? new Uint8Array(0)
    message.clientIdentity = object.clientIdentity ?? new Uint8Array(0)
    return message
  }
}

function createBaseGenerateKE2Reply(): GenerateKE2Reply {
  return { ke2: undefined, expectedClientMac: new Uint8Array(0), sessionKey: new Uint8Array(0) }
}

export const GenerateKE2Reply: MessageFns<GenerateKE2Reply> = {
  encode(message: GenerateKE2Reply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ke2 !== undefined) {
      OpaqueKe2.encode(message.ke2, writer.uint32(10).fork()).join()
    }
    if (message.expectedClientMac.length !== 0) {
      writer.uint32(18).bytes(message.expectedClientMac)
    }
    if (message.sessionKey.length !== 0) {
      writer.uint32(26).bytes(message.sessionKey)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateKE2Reply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseGenerateKE2Reply()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.ke2 = OpaqueKe2.decode(reader, reader.uint32())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.expectedClientMac = reader.bytes()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.sessionKey = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): GenerateKE2Reply {
    return {
      ke2: isSet(object.ke2) ? OpaqueKe2.fromJSON(object.ke2) : undefined,
      expectedClientMac: isSet(object.expectedClientMac)
        ? bytesFromBase64(object.expectedClientMac)
        : isSet(object.expected_client_mac)
          ? bytesFromBase64(object.expected_client_mac)
          : new Uint8Array(0),
      sessionKey: isSet(object.sessionKey) ? bytesFromBase64(object.sessionKey) : isSet(object.session_key) ? bytesFromBase64(object.session_key) : new Uint8Array(0)
    }
  },

  toJSON(message: GenerateKE2Reply): unknown {
    const obj: any = {}
    if (message.ke2 !== undefined) {
      obj.ke2 = OpaqueKe2.toJSON(message.ke2)
    }
    if (message.expectedClientMac.length !== 0) {
      obj.expectedClientMac = base64FromBytes(message.expectedClientMac)
    }
    if (message.sessionKey.length !== 0) {
      obj.sessionKey = base64FromBytes(message.sessionKey)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<GenerateKE2Reply>, I>>(base?: I): GenerateKE2Reply {
    return GenerateKE2Reply.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<GenerateKE2Reply>, I>>(object: I): GenerateKE2Reply {
    const message = createBaseGenerateKE2Reply()
    message.ke2 = object.ke2 !== undefined && object.ke2 !== null ? OpaqueKe2.fromPartial(object.ke2) : undefined
    message.expectedClientMac = object.expectedClientMac ?? new Uint8Array(0)
    message.sessionKey = object.sessionKey ?? new Uint8Array(0)
    return message
  }
}

function createBaseServerFinishRequest(): ServerFinishRequest {
  return { ke3ClientMac: new Uint8Array(0), expectedClientMac: new Uint8Array(0) }
}

export const ServerFinishRequest: MessageFns<ServerFinishRequest> = {
  encode(message: ServerFinishRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ke3ClientMac.length !== 0) {
      writer.uint32(10).bytes(message.ke3ClientMac)
    }
    if (message.expectedClientMac.length !== 0) {
      writer.uint32(18).bytes(message.expectedClientMac)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerFinishRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseServerFinishRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.ke3ClientMac = reader.bytes()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.expectedClientMac = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): ServerFinishRequest {
    return {
      ke3ClientMac: isSet(object.ke3ClientMac) ? bytesFromBase64(object.ke3ClientMac) : isSet(object.ke3_client_mac) ? bytesFromBase64(object.ke3_client_mac) : new Uint8Array(0),
      expectedClientMac: isSet(object.expectedClientMac)
        ? bytesFromBase64(object.expectedClientMac)
        : isSet(object.expected_client_mac)
          ? bytesFromBase64(object.expected_client_mac)
          : new Uint8Array(0)
    }
  },

  toJSON(message: ServerFinishRequest): unknown {
    const obj: any = {}
    if (message.ke3ClientMac.length !== 0) {
      obj.ke3ClientMac = base64FromBytes(message.ke3ClientMac)
    }
    if (message.expectedClientMac.length !== 0) {
      obj.expectedClientMac = base64FromBytes(message.expectedClientMac)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<ServerFinishRequest>, I>>(base?: I): ServerFinishRequest {
    return ServerFinishRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<ServerFinishRequest>, I>>(object: I): ServerFinishRequest {
    const message = createBaseServerFinishRequest()
    message.ke3ClientMac = object.ke3ClientMac ?? new Uint8Array(0)
    message.expectedClientMac = object.expectedClientMac ?? new Uint8Array(0)
    return message
  }
}

function createBaseServerFinishReply(): ServerFinishReply {
  return { valid: false }
}

export const ServerFinishReply: MessageFns<ServerFinishReply> = {
  encode(message: ServerFinishReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.valid !== false) {
      writer.uint32(8).bool(message.valid)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerFinishReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseServerFinishReply()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.valid = reader.bool()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): ServerFinishReply {
    return { valid: isSet(object.valid) ? globalThis.Boolean(object.valid) : false }
  },

  toJSON(message: ServerFinishReply): unknown {
    const obj: any = {}
    if (message.valid !== false) {
      obj.valid = message.valid
    }
    return obj
  },

  create<I extends Exact<DeepPartial<ServerFinishReply>, I>>(base?: I): ServerFinishReply {
    return ServerFinishReply.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<ServerFinishReply>, I>>(object: I): ServerFinishReply {
    const message = createBaseServerFinishReply()
    message.valid = object.valid ?? false
    return message
  }
}

function createBaseCreateChangePasswordResponseRequest(): CreateChangePasswordResponseRequest {
  return {
    credentialIdentifier: new Uint8Array(0),
    oldPasswordKe1: undefined,
    newPasswordRegRequest: undefined,
    record: undefined,
    serverIdentity: new Uint8Array(0),
    clientIdentity: new Uint8Array(0)
  }
}

export const CreateChangePasswordResponseRequest: MessageFns<CreateChangePasswordResponseRequest> = {
  encode(message: CreateChangePasswordResponseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.credentialIdentifier.length !== 0) {
      writer.uint32(10).bytes(message.credentialIdentifier)
    }
    if (message.oldPasswordKe1 !== undefined) {
      OpaqueKe1.encode(message.oldPasswordKe1, writer.uint32(18).fork()).join()
    }
    if (message.newPasswordRegRequest !== undefined) {
      OpaqueCredentialRequest.encode(message.newPasswordRegRequest, writer.uint32(26).fork()).join()
    }
    if (message.record !== undefined) {
      OpaqueRecord.encode(message.record, writer.uint32(34).fork()).join()
    }
    if (message.serverIdentity.length !== 0) {
      writer.uint32(42).bytes(message.serverIdentity)
    }
    if (message.clientIdentity.length !== 0) {
      writer.uint32(50).bytes(message.clientIdentity)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateChangePasswordResponseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseCreateChangePasswordResponseRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.credentialIdentifier = reader.bytes()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.oldPasswordKe1 = OpaqueKe1.decode(reader, reader.uint32())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.newPasswordRegRequest = OpaqueCredentialRequest.decode(reader, reader.uint32())
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.record = OpaqueRecord.decode(reader, reader.uint32())
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.serverIdentity = reader.bytes()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.clientIdentity = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): CreateChangePasswordResponseRequest {
    return {
      credentialIdentifier: isSet(object.credentialIdentifier)
        ? bytesFromBase64(object.credentialIdentifier)
        : isSet(object.credential_identifier)
          ? bytesFromBase64(object.credential_identifier)
          : new Uint8Array(0),
      oldPasswordKe1: isSet(object.oldPasswordKe1) ? OpaqueKe1.fromJSON(object.oldPasswordKe1) : isSet(object.old_password_ke1) ? OpaqueKe1.fromJSON(object.old_password_ke1) : undefined,
      newPasswordRegRequest: isSet(object.newPasswordRegRequest)
        ? OpaqueCredentialRequest.fromJSON(object.newPasswordRegRequest)
        : isSet(object.new_password_reg_request)
          ? OpaqueCredentialRequest.fromJSON(object.new_password_reg_request)
          : undefined,
      record: isSet(object.record) ? OpaqueRecord.fromJSON(object.record) : undefined,
      serverIdentity: isSet(object.serverIdentity) ? bytesFromBase64(object.serverIdentity) : isSet(object.server_identity) ? bytesFromBase64(object.server_identity) : new Uint8Array(0),
      clientIdentity: isSet(object.clientIdentity) ? bytesFromBase64(object.clientIdentity) : isSet(object.client_identity) ? bytesFromBase64(object.client_identity) : new Uint8Array(0)
    }
  },

  toJSON(message: CreateChangePasswordResponseRequest): unknown {
    const obj: any = {}
    if (message.credentialIdentifier.length !== 0) {
      obj.credentialIdentifier = base64FromBytes(message.credentialIdentifier)
    }
    if (message.oldPasswordKe1 !== undefined) {
      obj.oldPasswordKe1 = OpaqueKe1.toJSON(message.oldPasswordKe1)
    }
    if (message.newPasswordRegRequest !== undefined) {
      obj.newPasswordRegRequest = OpaqueCredentialRequest.toJSON(message.newPasswordRegRequest)
    }
    if (message.record !== undefined) {
      obj.record = OpaqueRecord.toJSON(message.record)
    }
    if (message.serverIdentity.length !== 0) {
      obj.serverIdentity = base64FromBytes(message.serverIdentity)
    }
    if (message.clientIdentity.length !== 0) {
      obj.clientIdentity = base64FromBytes(message.clientIdentity)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<CreateChangePasswordResponseRequest>, I>>(base?: I): CreateChangePasswordResponseRequest {
    return CreateChangePasswordResponseRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<CreateChangePasswordResponseRequest>, I>>(object: I): CreateChangePasswordResponseRequest {
    const message = createBaseCreateChangePasswordResponseRequest()
    message.credentialIdentifier = object.credentialIdentifier ?? new Uint8Array(0)
    message.oldPasswordKe1 = object.oldPasswordKe1 !== undefined && object.oldPasswordKe1 !== null ? OpaqueKe1.fromPartial(object.oldPasswordKe1) : undefined
    message.newPasswordRegRequest = object.newPasswordRegRequest !== undefined && object.newPasswordRegRequest !== null ? OpaqueCredentialRequest.fromPartial(object.newPasswordRegRequest) : undefined
    message.record = object.record !== undefined && object.record !== null ? OpaqueRecord.fromPartial(object.record) : undefined
    message.serverIdentity = object.serverIdentity ?? new Uint8Array(0)
    message.clientIdentity = object.clientIdentity ?? new Uint8Array(0)
    return message
  }
}

function createBaseCreateChangePasswordResponseReply(): CreateChangePasswordResponseReply {
  return {
    oldPasswordKe2: undefined,
    expectedClientMac: new Uint8Array(0),
    sessionKey: new Uint8Array(0),
    newEvaluatedMessage: new Uint8Array(0),
    newServerPublicKey: new Uint8Array(0)
  }
}

export const CreateChangePasswordResponseReply: MessageFns<CreateChangePasswordResponseReply> = {
  encode(message: CreateChangePasswordResponseReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.oldPasswordKe2 !== undefined) {
      OpaqueKe2.encode(message.oldPasswordKe2, writer.uint32(10).fork()).join()
    }
    if (message.expectedClientMac.length !== 0) {
      writer.uint32(18).bytes(message.expectedClientMac)
    }
    if (message.sessionKey.length !== 0) {
      writer.uint32(26).bytes(message.sessionKey)
    }
    if (message.newEvaluatedMessage.length !== 0) {
      writer.uint32(34).bytes(message.newEvaluatedMessage)
    }
    if (message.newServerPublicKey.length !== 0) {
      writer.uint32(42).bytes(message.newServerPublicKey)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateChangePasswordResponseReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseCreateChangePasswordResponseReply()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.oldPasswordKe2 = OpaqueKe2.decode(reader, reader.uint32())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.expectedClientMac = reader.bytes()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.sessionKey = reader.bytes()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.newEvaluatedMessage = reader.bytes()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.newServerPublicKey = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): CreateChangePasswordResponseReply {
    return {
      oldPasswordKe2: isSet(object.oldPasswordKe2) ? OpaqueKe2.fromJSON(object.oldPasswordKe2) : isSet(object.old_password_ke2) ? OpaqueKe2.fromJSON(object.old_password_ke2) : undefined,
      expectedClientMac: isSet(object.expectedClientMac)
        ? bytesFromBase64(object.expectedClientMac)
        : isSet(object.expected_client_mac)
          ? bytesFromBase64(object.expected_client_mac)
          : new Uint8Array(0),
      sessionKey: isSet(object.sessionKey) ? bytesFromBase64(object.sessionKey) : isSet(object.session_key) ? bytesFromBase64(object.session_key) : new Uint8Array(0),
      newEvaluatedMessage: isSet(object.newEvaluatedMessage)
        ? bytesFromBase64(object.newEvaluatedMessage)
        : isSet(object.new_evaluated_message)
          ? bytesFromBase64(object.new_evaluated_message)
          : new Uint8Array(0),
      newServerPublicKey: isSet(object.newServerPublicKey)
        ? bytesFromBase64(object.newServerPublicKey)
        : isSet(object.new_server_public_key)
          ? bytesFromBase64(object.new_server_public_key)
          : new Uint8Array(0)
    }
  },

  toJSON(message: CreateChangePasswordResponseReply): unknown {
    const obj: any = {}
    if (message.oldPasswordKe2 !== undefined) {
      obj.oldPasswordKe2 = OpaqueKe2.toJSON(message.oldPasswordKe2)
    }
    if (message.expectedClientMac.length !== 0) {
      obj.expectedClientMac = base64FromBytes(message.expectedClientMac)
    }
    if (message.sessionKey.length !== 0) {
      obj.sessionKey = base64FromBytes(message.sessionKey)
    }
    if (message.newEvaluatedMessage.length !== 0) {
      obj.newEvaluatedMessage = base64FromBytes(message.newEvaluatedMessage)
    }
    if (message.newServerPublicKey.length !== 0) {
      obj.newServerPublicKey = base64FromBytes(message.newServerPublicKey)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<CreateChangePasswordResponseReply>, I>>(base?: I): CreateChangePasswordResponseReply {
    return CreateChangePasswordResponseReply.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<CreateChangePasswordResponseReply>, I>>(object: I): CreateChangePasswordResponseReply {
    const message = createBaseCreateChangePasswordResponseReply()
    message.oldPasswordKe2 = object.oldPasswordKe2 !== undefined && object.oldPasswordKe2 !== null ? OpaqueKe2.fromPartial(object.oldPasswordKe2) : undefined
    message.expectedClientMac = object.expectedClientMac ?? new Uint8Array(0)
    message.sessionKey = object.sessionKey ?? new Uint8Array(0)
    message.newEvaluatedMessage = object.newEvaluatedMessage ?? new Uint8Array(0)
    message.newServerPublicKey = object.newServerPublicKey ?? new Uint8Array(0)
    return message
  }
}

export type PublicService = typeof PublicService
export const PublicService = {
  health: {
    path: '/v0.Public/Health' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HealthRequest): Buffer => Buffer.from(HealthRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthRequest => HealthRequest.decode(value),
    responseSerialize: (value: HealthResponse): Buffer => Buffer.from(HealthResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthResponse => HealthResponse.decode(value)
  }
} as const

export interface PublicServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthRequest, HealthResponse>
}

export interface PublicClient extends Client {
  health(request: HealthRequest, callback: (error: ServiceError | null, response: HealthResponse) => void): ClientUnaryCall
  health(request: HealthRequest, metadata: Metadata, callback: (error: ServiceError | null, response: HealthResponse) => void): ClientUnaryCall
  health(request: HealthRequest, metadata: Metadata, options: Partial<CallOptions>, callback: (error: ServiceError | null, response: HealthResponse) => void): ClientUnaryCall
}

export const PublicClient = makeGenericClientConstructor(PublicService, 'v0.Public') as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PublicClient
  service: typeof PublicService
  serviceName: string
}

export type ZeroAccessService = typeof ZeroAccessService
export const ZeroAccessService = {
  /**
   * Registration phase, step 2 of 3:
   *   Server evaluates the OPRF on the client's blinded password.
   *   Derives the per-credential OPRF key from OPAQUE_SEED + credential_identifier.
   *   Returns the evaluated element and the server's long-term public key.
   *   RFC 9807 §5.1.2 — CreateRegistrationResponse
   */
  createRegistrationResponse: {
    path: '/v0.ZeroAccess/CreateRegistrationResponse' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateRegistrationResponseRequest): Buffer => Buffer.from(CreateRegistrationResponseRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateRegistrationResponseRequest => CreateRegistrationResponseRequest.decode(value),
    responseSerialize: (value: CreateRegistrationResponseReply): Buffer => Buffer.from(CreateRegistrationResponseReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateRegistrationResponseReply => CreateRegistrationResponseReply.decode(value)
  },
  /**
   * Authentication (AKE) phase, step 2 of 4:
   *   Server evaluates OPRF, masks the credential response, performs triple-DH,
   *   derives session keys, and produces a server MAC for mutual authentication.
   *   Returns KE2 + server state (expectedClientMac, sessionKey) for Redis storage.
   *   RFC 9807 §6.2.4 — GenerateKE2
   */
  generateKe2: {
    path: '/v0.ZeroAccess/GenerateKE2' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GenerateKE2Request): Buffer => Buffer.from(GenerateKE2Request.encode(value).finish()),
    requestDeserialize: (value: Buffer): GenerateKE2Request => GenerateKE2Request.decode(value),
    responseSerialize: (value: GenerateKE2Reply): Buffer => Buffer.from(GenerateKE2Reply.encode(value).finish()),
    responseDeserialize: (value: Buffer): GenerateKE2Reply => GenerateKE2Reply.decode(value)
  },
  /**
   * Authentication (AKE) phase, step 4 of 4:
   *   Server verifies the client MAC from KE3 using constant-time comparison.
   *   Both ke3_client_mac and expected_client_mac are 64-byte HMAC-SHA512 values.
   *   RFC 9807 §6.2.6 — ServerVerifyKE3
   */
  serverFinish: {
    path: '/v0.ZeroAccess/ServerFinish' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ServerFinishRequest): Buffer => Buffer.from(ServerFinishRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ServerFinishRequest => ServerFinishRequest.decode(value),
    responseSerialize: (value: ServerFinishReply): Buffer => Buffer.from(ServerFinishReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ServerFinishReply => ServerFinishReply.decode(value)
  },
  /**
   * Password change phase, step 2 of 4:
   *   Server simultaneously handles old-password AKE (GenerateKE2) and
   *   new-password registration response (CreateRegistrationResponse).
   *   Atomic: client must verify old password before new record is accepted.
   *   RFC 9807 — combined ChangePassword flow
   */
  createChangePasswordResponse: {
    path: '/v0.ZeroAccess/CreateChangePasswordResponse' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateChangePasswordResponseRequest): Buffer => Buffer.from(CreateChangePasswordResponseRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateChangePasswordResponseRequest => CreateChangePasswordResponseRequest.decode(value),
    responseSerialize: (value: CreateChangePasswordResponseReply): Buffer => Buffer.from(CreateChangePasswordResponseReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateChangePasswordResponseReply => CreateChangePasswordResponseReply.decode(value)
  }
} as const

export interface ZeroAccessServer extends UntypedServiceImplementation {
  /**
   * Registration phase, step 2 of 3:
   *   Server evaluates the OPRF on the client's blinded password.
   *   Derives the per-credential OPRF key from OPAQUE_SEED + credential_identifier.
   *   Returns the evaluated element and the server's long-term public key.
   *   RFC 9807 §5.1.2 — CreateRegistrationResponse
   */
  createRegistrationResponse: handleUnaryCall<CreateRegistrationResponseRequest, CreateRegistrationResponseReply>
  /**
   * Authentication (AKE) phase, step 2 of 4:
   *   Server evaluates OPRF, masks the credential response, performs triple-DH,
   *   derives session keys, and produces a server MAC for mutual authentication.
   *   Returns KE2 + server state (expectedClientMac, sessionKey) for Redis storage.
   *   RFC 9807 §6.2.4 — GenerateKE2
   */
  generateKe2: handleUnaryCall<GenerateKE2Request, GenerateKE2Reply>
  /**
   * Authentication (AKE) phase, step 4 of 4:
   *   Server verifies the client MAC from KE3 using constant-time comparison.
   *   Both ke3_client_mac and expected_client_mac are 64-byte HMAC-SHA512 values.
   *   RFC 9807 §6.2.6 — ServerVerifyKE3
   */
  serverFinish: handleUnaryCall<ServerFinishRequest, ServerFinishReply>
  /**
   * Password change phase, step 2 of 4:
   *   Server simultaneously handles old-password AKE (GenerateKE2) and
   *   new-password registration response (CreateRegistrationResponse).
   *   Atomic: client must verify old password before new record is accepted.
   *   RFC 9807 — combined ChangePassword flow
   */
  createChangePasswordResponse: handleUnaryCall<CreateChangePasswordResponseRequest, CreateChangePasswordResponseReply>
}

export interface ZeroAccessClient extends Client {
  /**
   * Registration phase, step 2 of 3:
   *   Server evaluates the OPRF on the client's blinded password.
   *   Derives the per-credential OPRF key from OPAQUE_SEED + credential_identifier.
   *   Returns the evaluated element and the server's long-term public key.
   *   RFC 9807 §5.1.2 — CreateRegistrationResponse
   */
  createRegistrationResponse(request: CreateRegistrationResponseRequest, callback: (error: ServiceError | null, response: CreateRegistrationResponseReply) => void): ClientUnaryCall
  createRegistrationResponse(request: CreateRegistrationResponseRequest, metadata: Metadata, callback: (error: ServiceError | null, response: CreateRegistrationResponseReply) => void): ClientUnaryCall
  createRegistrationResponse(
    request: CreateRegistrationResponseRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateRegistrationResponseReply) => void
  ): ClientUnaryCall
  /**
   * Authentication (AKE) phase, step 2 of 4:
   *   Server evaluates OPRF, masks the credential response, performs triple-DH,
   *   derives session keys, and produces a server MAC for mutual authentication.
   *   Returns KE2 + server state (expectedClientMac, sessionKey) for Redis storage.
   *   RFC 9807 §6.2.4 — GenerateKE2
   */
  generateKe2(request: GenerateKE2Request, callback: (error: ServiceError | null, response: GenerateKE2Reply) => void): ClientUnaryCall
  generateKe2(request: GenerateKE2Request, metadata: Metadata, callback: (error: ServiceError | null, response: GenerateKE2Reply) => void): ClientUnaryCall
  generateKe2(request: GenerateKE2Request, metadata: Metadata, options: Partial<CallOptions>, callback: (error: ServiceError | null, response: GenerateKE2Reply) => void): ClientUnaryCall
  /**
   * Authentication (AKE) phase, step 4 of 4:
   *   Server verifies the client MAC from KE3 using constant-time comparison.
   *   Both ke3_client_mac and expected_client_mac are 64-byte HMAC-SHA512 values.
   *   RFC 9807 §6.2.6 — ServerVerifyKE3
   */
  serverFinish(request: ServerFinishRequest, callback: (error: ServiceError | null, response: ServerFinishReply) => void): ClientUnaryCall
  serverFinish(request: ServerFinishRequest, metadata: Metadata, callback: (error: ServiceError | null, response: ServerFinishReply) => void): ClientUnaryCall
  serverFinish(request: ServerFinishRequest, metadata: Metadata, options: Partial<CallOptions>, callback: (error: ServiceError | null, response: ServerFinishReply) => void): ClientUnaryCall
  /**
   * Password change phase, step 2 of 4:
   *   Server simultaneously handles old-password AKE (GenerateKE2) and
   *   new-password registration response (CreateRegistrationResponse).
   *   Atomic: client must verify old password before new record is accepted.
   *   RFC 9807 — combined ChangePassword flow
   */
  createChangePasswordResponse(request: CreateChangePasswordResponseRequest, callback: (error: ServiceError | null, response: CreateChangePasswordResponseReply) => void): ClientUnaryCall
  createChangePasswordResponse(
    request: CreateChangePasswordResponseRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateChangePasswordResponseReply) => void
  ): ClientUnaryCall
  createChangePasswordResponse(
    request: CreateChangePasswordResponseRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateChangePasswordResponseReply) => void
  ): ClientUnaryCall
}

export const ZeroAccessClient = makeGenericClientConstructor(ZeroAccessService, 'v0.ZeroAccess') as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ZeroAccessClient
  service: typeof ZeroAccessService
  serviceName: string
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, 'base64'))
  } else {
    const bin = globalThis.atob(b64)
    const arr = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i)
    }
    return arr
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString('base64')
  } else {
    const bin: string[] = []
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte))
    })
    return globalThis.btoa(bin.join(''))
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin ? P : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
