// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v3.19.1
// source: v0/contract.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation
} from '@grpc/grpc-js'

export const protobufPackage = 'v0'

export interface HealthRequest {
  payload: string
}

export interface HealthResponse {
  payload: string
  data: string
}

function createBaseHealthRequest(): HealthRequest {
  return { payload: '' }
}

export const HealthRequest: MessageFns<HealthRequest> = {
  encode(message: HealthRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload !== '') {
      writer.uint32(10).string(message.payload)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseHealthRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.payload = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): HealthRequest {
    return { payload: isSet(object.payload) ? globalThis.String(object.payload) : '' }
  },

  toJSON(message: HealthRequest): unknown {
    const obj: any = {}
    if (message.payload !== '') {
      obj.payload = message.payload
    }
    return obj
  },

  create<I extends Exact<DeepPartial<HealthRequest>, I>>(base?: I): HealthRequest {
    return HealthRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<HealthRequest>, I>>(object: I): HealthRequest {
    const message = createBaseHealthRequest()
    message.payload = object.payload ?? ''
    return message
  }
}

function createBaseHealthResponse(): HealthResponse {
  return { payload: '', data: '' }
}

export const HealthResponse: MessageFns<HealthResponse> = {
  encode(message: HealthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload !== '') {
      writer.uint32(10).string(message.payload)
    }
    if (message.data !== '') {
      writer.uint32(18).string(message.data)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseHealthResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.payload = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.data = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): HealthResponse {
    return {
      payload: isSet(object.payload) ? globalThis.String(object.payload) : '',
      data: isSet(object.data) ? globalThis.String(object.data) : ''
    }
  },

  toJSON(message: HealthResponse): unknown {
    const obj: any = {}
    if (message.payload !== '') {
      obj.payload = message.payload
    }
    if (message.data !== '') {
      obj.data = message.data
    }
    return obj
  },

  create<I extends Exact<DeepPartial<HealthResponse>, I>>(base?: I): HealthResponse {
    return HealthResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<HealthResponse>, I>>(object: I): HealthResponse {
    const message = createBaseHealthResponse()
    message.payload = object.payload ?? ''
    message.data = object.data ?? ''
    return message
  }
}

export type PublicService = typeof PublicService
export const PublicService = {
  health: {
    path: '/v0.Public/Health',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: HealthRequest): Buffer => Buffer.from(HealthRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthRequest => HealthRequest.decode(value),
    responseSerialize: (value: HealthResponse): Buffer => Buffer.from(HealthResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthResponse => HealthResponse.decode(value)
  }
} as const

export interface PublicServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthRequest, HealthResponse>
}

export interface PublicClient extends Client {
  health(request: HealthRequest, callback: (error: ServiceError | null, response: HealthResponse) => void): ClientUnaryCall
  health(request: HealthRequest, metadata: Metadata, callback: (error: ServiceError | null, response: HealthResponse) => void): ClientUnaryCall
  health(request: HealthRequest, metadata: Metadata, options: Partial<CallOptions>, callback: (error: ServiceError | null, response: HealthResponse) => void): ClientUnaryCall
}

export const PublicClient = makeGenericClientConstructor(PublicService, 'v0.Public') as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PublicClient
  service: typeof PublicService
  serviceName: string
}

/**  */
export type ZeroAccessService = typeof ZeroAccessService
export const ZeroAccessService = {} as const

export interface ZeroAccessServer extends UntypedServiceImplementation {}

export interface ZeroAccessClient extends Client {}

export const ZeroAccessClient = makeGenericClientConstructor(ZeroAccessService, 'v0.ZeroAccess') as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ZeroAccessClient
  service: typeof ZeroAccessService
  serviceName: string
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin ? P : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
