module.exports = {
  apps: [
    {
      name: "peacekeeper-rust",
      script: "scripts/grpc-start.sh",
      interpreter: "bash",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      cwd: "./",
      env: {
        RUST_LOG: "info",
      },
      error_file: "logs/pm2-rust-error.log",
      out_file: "logs/pm2-rust-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "2G",
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: "peacekeeper-node",
      script: "_dist/src/server.js",
      interpreter: "node",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      env: {
        NODE_ENV: "production",
      },
      error_file: "logs/pm2-node-error.log",
      out_file: "logs/pm2-node-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "1G",
    },
  ],
};
